FROM alpine AS build
LABEL maintainer="paramsinghvc@gmail.com"
RUN apk add --update nodejs nodejs-npm
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM alpine AS ship
RUN apk add --update nodejs nodejs-npm
RUN npm install -g serve
COPY --from=build /app/build /app
EXPOSE 3000
CMD serve -s /app -l 3000